# Generated by Django 4.2.29 on 2026-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner'), ('evening_snack', 'Evening Snack')], max_length=20),
        ),
    ]
