# Generated by Django 4.2.29 on 2026-05-12 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0003_alter_waterlog_options_remove_waterlog_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner'), ('evening_snack', 'Evening Snack')], max_length=20)),
                ('image', models.ImageField(upload_to='meal_photos/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('detected_food_name', models.CharField(blank=True, max_length=200)),
                ('estimated_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('estimated_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('estimated_carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('estimated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_analyses', to='meals.meal')),
                ('meal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_analyses', to='meals.mealitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
