# Generated by Django 4.2.29 on 2026-03-14 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sugar_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sodium_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('openfoodfacts', 'Open Food Facts'), ('usda', 'USDA')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.foodcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='food_foodit_name_22c054_idx'), models.Index(fields=['barcode'], name='food_foodit_barcode_80cf21_idx'), models.Index(fields=['category'], name='food_foodit_categor_d2e149_idx')],
            },
        ),
    ]
